public class Achievments
{
    public static readonly Achievment[] LIST = {
        new ScoreAchievment{id = 1, name="ach_1", goal=500, earning = 100, playId="CgkItpnkssUKEAIQAg"},
        new GameAchievment{id = 2, name="ach_2", goal=5, earning = 100, playId="CgkItpnkssUKEAIQAw"},
        new BulbAchievment{id = 3, name="ach_3", goal=20, earning = 100, playId="CgkItpnkssUKEAIQBA"},
        new DailyGameAchievment{id = 4, name="ach_4", goal=3, earning = 100, playId="CgkItpnkssUKEAIQBQ"}, 
        new DeathAchievment{id = 5, name="ach_5", minimum=500 , goal=650, earning = 100, playId="CgkItpnkssUKEAIQBg"},
        new ScoreAchievment{id = 6, name="ach_6", goal=750, earning = 100, playId="CgkItpnkssUKEAIQBw"},
        new GameAchievment{id = 7, name="ach_7", goal=20, earning = 100, playId="CgkItpnkssUKEAIQCA"},
        new BulbAchievment{id = 8, name="ach_9", goal=40, earning = 100, playId="CgkItpnkssUKEAIQCg"},
        new ScoreWithAllEnergyAchievment{id = 9, name="ach_10", goal=5, earning = 100, playId="CgkItpnkssUKEAIQCw"},
        new EnergyDownAchievment{id = 10, name="ach_11", goal=1, earning = 100, playId="CgkItpnkssUKEAIQDA"},
        new ScoreAchievment{id = 11, name="ach_12", goal=1000, earning = 150, playId="CgkItpnkssUKEAIQDQ"},
        new DailyGameAchievment{id = 12, name="ach_8", goal=5, earning = 100, playId="CgkItpnkssUKEAIQCQ"},
        new SpeedDownAchievment{id = 13, name="ach_13", goal=1, earning = 100, playId="CgkItpnkssUKEAIQDg"},
        new SkinAchievment{id = 14, name="ach_14", goal=1, earning = 150, playId="CgkItpnkssUKEAIQDw"},
        new EnergyUpAchievment{id = 15, name="ach_15", goal=1, earning = 100, playId="CgkItpnkssUKEAIQEA"},
        new DeathAchievment{id = 16, name="ach_16", minimum=800 , goal=950, earning = 100, playId="CgkItpnkssUKEAIQEQ"},
        new ScoreWithAllEnergyAchievment{id = 17, name="ach_17", goal=8, earning = 100, playId="CgkItpnkssUKEAIQEg"},
        new SpeedUpAchievment{id = 18, name="ach_18", goal=1, earning = 100, playId="CgkItpnkssUKEAIQEw"},
        new ScoreAchievment{id = 19, name="ach_19", goal=1500, earning = 200, playId="CgkItpnkssUKEAIQFA"},
        new EnergyUpAchievment{id = 20, name="ach_20", goal=5, earning = 150, playId="CgkItpnkssUKEAIQFQ"},
        new DeathAchievment{id = 21, name="ach_21", minimum=1150 , goal=1250, earning = 100, playId="CgkItpnkssUKEAIQFg"},
        new SkinAchievment{id = 22, name="ach_22", goal=2, earning = 150, playId="CgkItpnkssUKEAIQFw"},
        new SpeedDownAchievment{id = 23, name="ach_23", goal=5, earning = 150, playId="CgkItpnkssUKEAIQGA"},
        new ScoreWithAllEnergyAchievment{id = 24, name="ach_24", goal=12, earning = 100, playId="CgkItpnkssUKEAIQGQ"},
        new BulbAchievment{id = 25, name="ach_25", goal=60, earning = 150, playId="CgkItpnkssUKEAIQGg"},
        new EnergyDownAchievment{id = 26, name="ach_26", goal=5, earning = 150, playId="CgkItpnkssUKEAIQGw"},
        new DeathAchievment{id = 27, name="ach_27", minimum=1400 , goal=1550, earning = 100, playId="CgkItpnkssUKEAIQHA"},
        new SpeedUpAchievment{id = 28, name="ach_28", goal=5, earning = 150, playId="CgkItpnkssUKEAIQHQ"},
        new ScoreWithAllEnergyAchievment{id = 29, name="ach_29", goal=15, earning = 100, playId="CgkItpnkssUKEAIQHg"},
    };
}